version: "3"

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dbpassword
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
